function [ctrltorque_coils, dipoleApplied, power_coils] = magnetorquers(b_eciTrue, qTrue, dipole)
% Calculate real control torque coils are able to deliver taking into
% account underactuation of the system and max value of magnetic dipole
% each coil can generate
% frequency of turning coils on/off is included in 'freq' variable taking
% into account the fact that in terms of satellite dynamics, the mean dipole
% generated by coils is important

global selectcoils maxdipole_xy maxdipole_z freq power_xy power_z;

A_i2s = q2m(qTrue);
b_sTrue = A_i2s * b_eciTrue * 1e-9;

% check if saturated -> if so, scale output
maxcomp = max(abs(dipole));

if maxcomp <= maxdipole_xy
elseif abs(dipole(1)) == maxcomp || abs(dipole(2)) == maxcomp || ((abs(dipole(3)) <= maxdipole_z) && ...
        (abs(dipole(1)) > maxdipole_xy || abs(dipole(2)) > maxdipole_xy))
    max_xy = max(abs(dipole(1)), abs(dipole(2)));
    dipole = dipole * maxdipole_xy / max_xy;
else
    dipole = dipole * maxdipole_z / maxcomp;
end

if abs(dipole(1)) > maxdipole_xy || abs(dipole(2)) > maxdipole_xy
    max_xy = max(abs(dipole(1)), abs(dipole(2)));
    dipole = dipole * maxdipole_xy / max_xy;
end

dipoleApplied = freq * selectcoils * dipole;
ctrltorque_coils = skew(dipoleApplied) * b_sTrue;
power_coils = power_xy*abs(dipoleApplied(1)) + power_xy*abs(dipoleApplied(2)) + power_z*abs(dipoleApplied(3));
    


